accounts/urls.py
from django.urls import path,include
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('change_profile/', views.change_profile, name='change_profile'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

actors/urls.py
from django.urls import path
from . import views

app_name="actors"

urlpatterns = [
    path('',views.search, name="search"),
    path('id_<int:actor_id>/',views.detail, name="detail"),
    path('id_<int:actor_id>/like', views.like_actor, name="like"),
    path('recommand/movie/',views.recommand_movie, name="recommand_movie"),
    path('recommand/actor/',views.recommand_actor, name="recommand_actor"),
    path('viewed/<int:movie_id>/',views.viewed_movie, name="viewed_movie"),
    path('id_<int:actor_id>/rating/', views.create_rating, name="create_rating"),
    path('id_<int:actor_id>/rating/<int:rating_id>/', views.update_rating, name="update_rating"),
    path('id_<int:actor_id>/rating/<int:rating_id>/delete/', views.delete_rating, name="delete_rating"),
    path('create/',views.create_actor, name="create_actor"),
    path('id_<int:actor_id>/update/',views.edit_actor, name="edit_actor"),
]

ebaeu/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from rest_framework_swagger.views import get_swagger_view
from accounts import views as accounts_views
from actors import views as actors_views

schema_view = get_swagger_view(title='Movie API')

urlpatterns = [
    url('api/v1/docs', schema_view),
    path('', actors_views.index, name='main'),
    path('admin/', admin.site.urls),
    path('actors/', include('actors.urls')),
    path('accounts/', include('accounts.urls')),
    path('@<str:username>/', accounts_views.profile, name='profile'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")


class Profile(models.Model):
    description = models.TextField(blank=True) 
    nickname = models.CharField(max_length=30, blank=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="profile")
    
    def __str__(self):
        return f"<{self.user.username}의 프로필, nickname: {self.nickname}, description: {self.description}>"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Profile


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['description', 'nickname']
        widgets = {
            'description':forms.Textarea(attrs={'placeholder':'자기소개를 작성해 주세요'}),
            'nickname':forms.TextInput(attrs={'placeholder':'닉네임을 작성해 주세요'})
        }

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm, ProfileForm
from django.contrib.auth.decorators import login_required
from .models import Profile


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            auth_login(request, user)
            return redirect('profile', request.user.username)
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/form.html', {'form': form, 'name': 'SignUp'})

  
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('profile', request.user.username)
        return redirect('accounts:login')
    else:
        form = AuthenticationForm()
        return render(request, 'accounts/form.html', {'form': form, 'name': 'Login'})


def logout(request):
    auth_logout(request)
    return redirect('main')


@login_required        
def follow(request, user_id):
    person = get_object_or_404(get_user_model(), id=user_id)
    if request.user in person.followers.all():
        person.followers.remove(request.user)
    else :
        person.followers.add(request.user)
    return redirect('profile', person.username)


def profile(request, username):
    profile = get_object_or_404(get_user_model(), username=username)
    return render(request, 'accounts/profile.html', {'profile': profile})


@login_required 
def change_profile(request):
    if request.method == "POST":
        profile_form = ProfileForm(data=request.POST, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('profile', request.user.username)
    else:
        profile_form = ProfileForm(instance=request.user.profile)
        return render(request, 'accounts/form.html', {'form':profile_form, 'name': 'My Profile'})

accounts/templates/accounts/form.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block title %}
  {{ name }}
{% endblock %}

{% block body %}
  <div class="col-6 offset-3">
    <h1 class="my-4">{{ name }}</h1>
    <form method='POST'>
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type=submit class='btn btn-primary'>{{ name }}</button>
      {% endbuttons %}
    </form>
  </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}
  {{ profile.username }}님의 프로필
{% endblock %}

{% block body %}
  <div class="row my-5">
    <div class="col-5">
      <div class="d-flex align-items-center justify-content-center">
        <h2>@{{ profile.username }}</h2>
      </div>
      <div class="d-flex align-items-center justify-content-center">
        {% if user != profile %}
          {% if user in profile.followers.all %}
              <a class="btn btn-warning btn-sm" href="{% url 'accounts:follow' profile.id %}">팔로우 취소</a>
            {% else %}
              <a class="btn btn-success btn-sm" href="{% url 'accounts:follow' profile.id %}">팔로우</a>
          {% endif %}
          {% else %}
          <a href="{% url 'accounts:change_profile' %}" class="btn btn-info btn-sm">프로필 수정</a>
        {% endif %}
      </div>
    </div>
    <div class="col-7">
      <strong>
        {{ profile.profile.nickname }}
      </strong>
      <div>
        {{ profile.profile.description }}
      </div>
      <hr>
      <div>
        <span class='mr-3' data-toggle="modal" data-target="#followerModal">팔로워: {{ profile.followers.count }}명</span>
        <span class='ml-3' data-toggle="modal" data-target="#followingModal">팔로우: {{ profile.followings.count }}명</span>
      </div>
    </div>
  </div>
  <div class="my-5">
    {% if user == profile %}
      <h3>내가 좋아하는 배우입니다.</h3>
    {% else %}
      <h3>{{ profile.username }}님이 좋아하는 배우입니다.</h3>
    {% endif %}
    {% if profile.like_actors.all %}
      <div class="row">
        {% for actor in profile.like_actors.all %}
        <div class="col-2 px-1" style="width: 18rem;">
          <div class="card px-0 my-1">
            <img src="{{ actor.image }}" class="card-img-top" alt="{{ actor.name }}">
            <div class="card-body" style="padding: 1rem;">
              <p class="card-text">{{ actor.name }}</p>
              <a href="{% url 'actors:detail' actor.id %}" class="btn btn-success btn-sm">바로가기</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    {% else %}
      <div class="blank">
        <h4>좋아하는 배우가 없습니다.</h4>
      </div>
    {% endif %}
  </div>
  <div class="my-5">
    {% if user == profile %}
      <h3>내가 본 영화입니다.</h3>
    {% else %}
      <h3>{{ profile.username }}님이 본 영화입니다.</h3>
    {% endif %}
    {% if profile.viewed_movies.all %}
      <div class="row">
        {% for movie in profile.viewed_movies.all %}
        
        {% load humanize %}
<!-- 영화 카드 시작 -->
<div class="col-4 px-1" style="width: 18rem;">
    <div class="card px-0 my-1" >
      <img src={{movie.poster_URL}} 
      class="card-img-top" 
      alt="poster"
      data-target="#movie-modal{{movie.id}}"
      data-toggle="modal"
      >
      <div class="card-body" style="padding: 1rem;">
        <h5 class="card-title mb-1">{{movie.title}}</h5>
        <span class="badge badge-primary" style="font-size: 13px">{{movie.score}}</span>
        <p class="card-text"><small class="text-muted">{{movie.open_date}}</small></p>
        <p class="card-text"><small class="text-muted">
          {% for genre in movie.genres.all %}
            {{genre.type}}   
          {% endfor %}
        </small></p>
      </div>
    </div>
  </div>
  <!-- 영화 카드 끝 -->
  <!-- 영화 모달 시작-->
  <div class="modal fade" id="movie-modal{{movie.id}}" tabindex="-1" role="dialog" aria-labelledby="MovieModalLabel{{movie.id}}" aria-hidden="true">
      <div class="modal-dialog" role="document" style="width: 450px;">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="MovieModalLabel{{movie.id}}">{{movie.title}}</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <img src={{movie.poster_URL}}
              class="card-img-top" 
              alt="poster"
              >
              <div class="modal-body">                    
                  <p><i class="fas fa-star-half-alt"></i> {{movie.score}} / 10</p>
                  <p><i class="fas fa-users"></i> {{movie.audience|intcomma}} 명</p>
                  <p><i class="fas fa-won-sign"></i> {{movie.sales|intcomma}} 원</p>
                  <p><hr></p>
                  <p><i class="fas fa-theater-masks"></i> 
                    {% for actor in movie.actors.all %} 
                      <a href="{% url 'actors:detail' actor.id %}">{{actor.name}} </a>
                    {% endfor %}
                  </p> 
                  <p><hr></p>
                  <p>{{movie.summary}}</p>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
          </div>
      </div>
  </div>
  <!-- 영화 모달 끝 -->

        {% endfor %}
      </div>
    {% else %}
      <div class="blank">
        <h4>등록된 영화가 없습니다.</h4>
      </div>
    {% endif %}
  </div>
{% include 'follow_modal.html' %}
{% endblock %}