accounts/urls.py
from django.urls import path,include
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('change_profile/', views.change_profile, name='change_profile'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

actors/urls.py
from django.urls import path
from . import views

app_name="actors"

urlpatterns = [
    path('',views.search, name="search"),
    path('id_<int:actor_id>/',views.detail, name="detail"),
    path('id_<int:actor_id>/like', views.like_actor, name="like"),
    path('recommand/movie/',views.recommand_movie, name="recommand_movie"),
    path('recommand/actor/',views.recommand_actor, name="recommand_actor"),
    path('viewed/<int:movie_id>/',views.viewed_movie, name="viewed_movie"),
    path('id_<int:actor_id>/rating/', views.create_rating, name="create_rating"),
    path('id_<int:actor_id>/rating/<int:rating_id>/', views.update_rating, name="update_rating"),
    path('id_<int:actor_id>/rating/<int:rating_id>/delete/', views.delete_rating, name="delete_rating"),
    path('create/',views.create_actor, name="create_actor"),
    path('id_<int:actor_id>/update/',views.edit_actor, name="edit_actor"),
]

ebaeu/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from rest_framework_swagger.views import get_swagger_view
from accounts import views as accounts_views
from actors import views as actors_views

schema_view = get_swagger_view(title='Movie API')

urlpatterns = [
    url('api/v1/docs', schema_view),
    path('', actors_views.index, name='main'),
    path('admin/', admin.site.urls),
    path('actors/', include('actors.urls')),
    path('accounts/', include('accounts.urls')),
    path('@<str:username>/', accounts_views.profile, name='profile'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!--static-->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--font-->
    <link href="https://fonts.googleapis.com/css?family=Jua|Yeon+Sung&amp;subset=korean" rel="stylesheet">
    <!--bootstrap-->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <!--fontawsome-->
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
      integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
      crossorigin="anonymous"
    />
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <title>{% block title %}{% endblock %}</title>
    <style type="text/css">
      #main_header{
        background-image: url('{% static "/image/header2.jpg" %}');
      }
      #movie_header{
        background-image: url('{% static "/image/header1.png" %}');
      }
      #actor_header{
        background-image: url('{% static "/image/header3.jpg" %}');
      }
      #search_header{
        background-image: url('{% static "/image/header4.jpg" %}');
        color: #8b008b;
      }
      #detail_header{
        background-image: url('{% static "/image/header0.jpg" %}');
      }
    </style>
  </head>
  <body>
    <nav>
      {% include 'nav.html' %}
    </nav>
    <header class="header" style="text-align:center;" id="detail_header">
        <h2></h2>       
    </header>
    <div class="fadein container">
      {% block body %} 
      {% endblock %}
    </div>
    <div class="d-flex justify-content-center align-items-center" style="height:75px;"><small class="text-muted text-center" style="font-size:15px;">- ebaeu 2019 -</small></div>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <script>
      const header = document.querySelector('header')
      const URL = document.URL
      if(URL.includes('recommand/actor')){
        header.id="actor_header"
        header.children[0].innerHTML="<h1>당신이 본 영화에 등장하는<br>'이 배우'를 추천해 드립니다</h1>"
      }else if(URL.includes('recommand/movie')){
        header.id="movie_header"
        header.children[0].innerHTML="<h1>당신이 좋아하는 '이 배우'가 출연한<br>영화를 추천해 드립니다</h1>"
      }else if(URL.includes('actors/id_')){
        header.id="detail_header"
        header.children[0].innerHTML="<h1>'이 배우'를 아시나요?</h1>"
      }else if(URL.includes('actors/?q')){
        header.id="search_header"
        header.children[0].innerHTML="<h1>당신이 검색한 '이 배우'입니다</h1>"
      }else if(URL.includes('actors/create')){
        header.children[0].innerHTML="<h1>배우 정보 등록</h1>"
      }else if(URL.includes('/update')){
        header.children[0].innerHTML="<h1>배우 정보 수정</h1>"
      }else if(URL.includes('accounts/login')){
        header.children[0].innerHTML="<h1>로그인</h1>"
      }else if(URL.includes('accounts/singup')){
        header.children[0].innerHTML="<h1>'이 배우' 회원가입</h1>"
      }else if(URL.includes('accounts/change_profile')){
        header.children[0].innerHTML="<h1>회원정보를 수정하세요</h1>"
      }else if(URL.includes('@')){
        header.children[0].innerHTML="<h1>회원정보</h1>"
      }else{
        header.id="main_header"
        header.children[0].innerHTML="<h1>'이 배우'가 출연하는 영화는<br>믿고 볼 수 있을거에요</h1>"
      }
      
    </script>
  </body>
</html>

templates/follow_modal.html
<div class="modal fade" id="followingModal" tabindex="-1" role="dialog" aria-labelledby="followingModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="followingModalTitle">Followers</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="list-group">
          {% if profile.followings.all %}
            {% for person in profile.followings.all %}  
              <li class="list-group-item">
                <a href="{% url 'profile' person.username %}">@{{ person.username }}</a>
              </li>
            {% endfor %}
          {% else %}
            <div class="blank">
              <h4>팔로잉이 없습니다.</h4>
            </div>
          {% endif %}
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="followerModal" tabindex="-1" role="dialog" aria-labelledby="followerModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="followerModalTitle">Followings</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="list-group">
          {% if profile.followers.all %}
            {% for person in profile.followers.all %}  
              <li class="list-group-item">
                <a href="{% url 'profile' person.username %}">@{{ person.username }}</a>
              </li>
            {% endfor %}
          {% else %}
            <div class="blank">
              <h4>팔로워가 없습니다.</h4>
            </div>
          {% endif %}
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

templates/like_modal.html
<div class="modal fade" id="likeModal" tabindex="-1" role="dialog" aria-labelledby="likeModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="likeModalTitle">Followings</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="list-group">
          {% if actor.like_users.all %}
            {% for person in actor.like_users.all %}  
              <li class="list-group-item">
                <a href="{% url 'profile' person.username %}">@{{ person.username }}</a>
              </li>
            {% endfor %}
          {% else %}
            <div class="blank">
              <h4>'이 배우'를 좋아하는 사람이 없습니다.</h4>
            </div>
          {% endif %}
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

templates/movie_modal.html
{% load humanize %}
<!-- 영화 모달 시작-->
<div class="modal fade" id="movie-modal{{movie.id}}" tabindex="-1" role="dialog"
  aria-labelledby="MovieModalLabel{{movie.id}}" aria-hidden="true">
  <div class="modal-dialog" role="document" style="width: 450px;">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="MovieModalLabel{{movie.id}}">{{movie.title}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <img src={{movie.poster_URL}} class="card-img-top" alt="poster">
      <div class="modal-body">
        <p><i class="fas fa-star-half-alt"></i> {{movie.score}} / 10</p>
        <p><i class="fas fa-users"></i> {{movie.audience|intcomma}} 명</p>
        <p><i class="fas fa-won-sign"></i> {{movie.sales|intcomma}} 원</p>
        <p>
          <hr>
        </p>
        <p><i class="fas fa-theater-masks"></i>
          {% for actor in movie.actors.all %}
          <a href="{% url 'actors:detail' actor.id %}">{{actor.name}} </a>
          {% endfor %}
        </p>
        <p>
          <hr>
        </p>
        <p>{{movie.summary}}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- 영화 모달 끝 -->

templates/nav.html
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'main' %}"><i class="far fa-star"></i>Ebaeu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main' %}"><i class="fas fa-home"></i>메인</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'actors:recommand_movie' %}">배우<i class="fas fa-long-arrow-alt-right"></i>영화</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'actors:recommand_actor' %}">영화<i class="fas fa-long-arrow-alt-right"></i>배우</a>
        </li>
      </ul>
      <ul class="navbar-nav">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' user.username %}">{{ user.username }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i><span class="ml-1">로그아웃</span></a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}"><i class="fas fa-sign-in-alt"></i><span class="ml-1">로그인</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}"><i class="fas fa-user-plus"></i><span>회원가입</span></a>
        </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'actors:search' %}" method="get">
      <input class="form-control mr-sm-2" type="search" placeholder="배우를 검색해 보세요" aria-label="Search" name='q'>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>